spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${USER_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/user_service}
    username: ${USER_SERVICE_DB_USERNAME:user_service}
    password: ${USER_SERVICE_DB_PASSWORD:user_service}
    hikari:
      initialization-fail-timeout: -1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot.allow_jdbc_metadata_access: false
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
server:
  port: 8081
